require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

# Disable RSpec cops that are crashing
RSpec:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y

Metrics/AbcSize:
  Max: 18

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Max: 100
